services:
  - type: web
    name: insertionordersmart
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 180 --workers 2 --threads 4
    envVars:
      - key: ORDER_COUNTER_CLOUDINARY_ID
        value: smart1_system/order_counter.json
      - key: GHL_WEBHOOK_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: BRANDFETCH_API_KEY
        sync: false
      - key: BRANDFETCH_CLIENT_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-5-mini
